### ISSUE TITLE
Build fails on MacOS

### ISSUE THREAD

**Issue by sourcedelica** [tyleradams/json-toolkit#4]
The build runs 
```
sudo apt install -y libpq-dev
```
This doesn't work on MacOS.  It also won't work on Fedora/Centos/RHEL.

**Comment by tyleradams** [comment]
Thanks for the catch. Unfortunately, I don't have a macOS machine available
to test a change with. Since you found this, could you submit a PR to
handle proper installations for macOS? Bonus points if the check also
handles other linux distros.

 Tyler
